#!/bin/bash
#SBATCH --account=rrg-ziels
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=8G
#SBATCH --time=2:0:0
#SBATCH --job-name=anvio-scgs
#SBATCH --output=%x.out


#get allocation and load modules
#salloc --time=2:0:0 --account=rrg-ziels --ntasks=12 --mem-per-cpu=8G
module load python scipy-stack diamond hmmer prodigal
source ~/projects/rrg-ziels/shared_tools/virtual_envs/anvio_7.0/bin/activate

#generate contigs database
 anvi-gen-contigs-database -f ../assembly.fasta -o ./contigs.db -n 'SAOB_ONT_v1' -T 12
 anvi-run-hmms -c ./contigs.db --num-threads 12